### Write a function so that the columns of the output matrix are powers of the input vector. 
 
### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 
 
### HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde. 

In [13]:
import numpy as np

def vander_matrix(inputvec, N, increasing = False): # this function takes the input of a vector, 
                                                    #number of output columns and order of the powers of the column
    if not increasing:
        arry = []
        for i in inputvec:
            for j in range(N):
                arry.append((i**(N-j-1))) # when increasing false generates array
        out_matrx =  np.array(arry).reshape(inputvec.size, N) # array converts to matrix and reshape it
    elif increasing:
        arry = []
        for i in inputvec:
            for j in range(N):
                arry.append((i**(j))) # when increasing true generates array
        out_matrx =  np.array(arry).reshape(inputvec.size, N) # array converts to matrix and reshape it
    return out_matrx
        
inputvec = np.array([1,3,5,7,9,11])
N = len(inputvec) # if number of output columns are not given it  will generate a square array


In [14]:
print('Output: Vandermonde matrix of a given vector when #of output colums 3 and increasing = False: ')
vander_matrix(inputvec, 3, False)

Output: Vandermonde matrix of a given vector when #of output colums 3 and increasing = False: 


array([[  1,   1,   1],
       [  9,   3,   1],
       [ 25,   5,   1],
       [ 49,   7,   1],
       [ 81,   9,   1],
       [121,  11,   1]])

In [15]:
print('Output: Vandermonde matrix of a given vector when #of output colums 3 and increasing = True: ')
vander_matrix(inputvec, 3, True)

Output: Vandermonde matrix of a given vector when #of output colums 3 and increasing = True: 


array([[  1,   1,   1],
       [  1,   3,   9],
       [  1,   5,  25],
       [  1,   7,  49],
       [  1,   9,  81],
       [  1,  11, 121]])

In [16]:
print('Output: Vandermonde matrix of a given vector when #of output colums not given and increasing = True: ')
vander_matrix(inputvec, N, True)

Output: Vandermonde matrix of a given vector when #of output colums not given and increasing = True: 


array([[     1,      1,      1,      1,      1,      1],
       [     1,      3,      9,     27,     81,    243],
       [     1,      5,     25,    125,    625,   3125],
       [     1,      7,     49,    343,   2401,  16807],
       [     1,      9,     81,    729,   6561,  59049],
       [     1,     11,    121,   1331,  14641, 161051]])

In [17]:
print('Output: Vandermonde matrix of a given vector when #of output colums not given and increasing = False: ')
vander_matrix(inputvec, N, False)

Output: Vandermonde matrix of a given vector when #of output colums not given and increasing = False: 


array([[     1,      1,      1,      1,      1,      1],
       [   243,     81,     27,      9,      3,      1],
       [  3125,    625,    125,     25,      5,      1],
       [ 16807,   2401,    343,     49,      7,      1],
       [ 59049,   6561,    729,     81,      9,      1],
       [161051,  14641,   1331,    121,     11,      1]])

### Problem Statement 2: 
 
#### Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: 
#### The moving average sequence has n-k+1 elements as shown below. 
 
#### The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
 
#### i 1  2  3  4  5  6  7  8  9 10  ===== == == == == == == == == == ==  Input 10 20 30 40 50 60 70 80 90 100
#### y1      25 = (10+20+30+40)/4
#### y2      35 = (20+30+40+50)/4
#### y3      45 = (30+40+50+60)/4
#### y4      55 = (40+50+60+70)/4
#### y5      65 = (50+60+70+80)/4
#### y6      75 = (60+70+80+90)/4
#### y7      85 = (70+80+90+100)/4 

#### Thus, the moving average sequence has n-k+1=10-4+1=7 values.

### Question: Write a function to find moving average in an array over a window:
### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [2]:
import numpy as np

def moving_average(inarr, size): # takes the input of array and window size
    
    avg_lst = []
    seq_val = len(inarr)-size+1 # calculating the moving average sequence values
    for i in range(seq_val): # outer forloop depends on sequence value
        lst = inarr[i:(size+i)] # slicing array dynamically   
        sum = 0        
        for j in range(len(lst)): # inner forloop calculates the moving average
            sum += lst[j]
        avg_lst.append(sum/size) # moving average values are appended in the empty list avg_lst
    return avg_lst
        

arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] # input array
inarr = np.array(arr)
size = 3
print('Moving Average of the Given Array:')
np.array(moving_average(inarr, size)).round(2) # output array


Moving Average of the Given Array:


array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])